name: Hello, World

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo 'Build started...'

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Testing suite
        run: echo 'running test cases...'

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Deploy process
        run: |
          echo 'Tests passed'
          echo 'Running deploy process'
